<?php header ("Content-type: image/png");
    include ('Odcinek.class.php');
    $p1 = new Odcinek();
    $p2 = new Odcinek();
    $p3 = new Odcinek();
    $handle = ImageCreate (200, 200) or die ("Cannot Create image");
    $bg_color = ImageColorAllocate ($handle, 0, 0, 0);
    $txt_color = ImageColorAllocate ($handle, 255, 255, 255);
    $p1->drawLine($handle);
    $p2->drawLine($handle);
    $p3->drawLine($handle);
    //ImageString ($handle, 100, 0, 130, "|AB|: ".$p1->liczDlugosc(), $txt_color);
    //ImageString ($handle, 100, 0, 150, "A: ".$p1->getX1()." ".$p1->getY1(), $txt_color);
    //ImageString ($handle, 100, 0, 170, "B: ".$p1->getX2()." ".$p1->getY2(), $txt_color);
    ImagePng ($handle);